-- AI-generated communications summary shown at the top of the factory drawer
-- Communications section (regenerated by Claude; cached here).
alter table public.factories add column if not exists ai_comms_summary text;
alter table public.factories add column if not exists ai_comms_summary_at timestamptz;
